version: '3.4'

services:
  frontend:
    image: node:14-alpine
    working_dir: /app
    environment:
      SNOWPACK_PUBLIC_BASE_URL: http://localhost:9000
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 8000:8000

  backend:
    image: strapi/strapi:3.5.0-alpine
    volumes:
      - backend_node_modules:/srv/app/node_modules
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: rogalik
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      DATABASE_USERNAME: rogalikuser
      DATABASE_PASSWORD: rogaliksecret
    ports:
      - 9000:1337
      - 1337:1337

  database:
    image: postgres:13-alpine
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rogaliksecret
      POSTGRES_USER: rogalikuser
      POSTGRES_DB: rogalik

volumes:
  frontend_node_modules:
  backend_node_modules:
  database_data:

