version: '3.4'

services:
  proxy:
    image: caddy:2.3.0-alpine
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8000:8000

  frontend:
    image: node:14-alpine
    working_dir: /app
    environment:
      SNOWPACK_PUBLIC_BASE_URL: http://localhost:8000/api
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules
    expose:
      - 8000

  backend:
    build:
      context: ../../api
      dockerfile: ../docker/development/backend/Dockerfile
    environment:
      DATABASE_URL: postgres://rogalikuser:rogaliksecret@database/database:5432
      ROCKET_DATABASES: '{diesel={url="postgres://rogalikuser:rogaliksecret@database/database:5432"}}'
    volumes:
      - ../../api:/app
    links:
      - database
    expose:
      - 9000
    command: bash -c "./tools/wait-for-it.sh database:5432 -q -- diesel setup && cargo watch -x run"

  database:
    image: postgres:13-alpine
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rogaliksecret
      POSTGRES_USER: rogalikuser
      POSTGRES_DB: rogalik

volumes:
  frontend_node_modules:
  database_data:

