version: '3.4'

services:
  reverse_proxy:
    image: caddy:2-alpine
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8000:8000

  api:
    image: cosmtrek/air
    environment: 
      air_wd: /go/public
    expose:
      - 8000
    volumes:
      - ../../api:/go/public
    command: gow run /go/public/main.go

  frontend:
    image: node:12-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    expose:
      - 8000
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:

